---

- name: check conectivity
  ping:
  delegate_to: cephadmin

- name: create .ssh for ceph user
  file: 
    path: ~ceph/.ssh
    state: directory
    force: no
    mode: 700

- name: create .ssh for ceph user
  copy: 
    content: ""
    dest: ~ceph/.ssh/authorized_keys
    force: no

- name: turn off strict host key checking
  lineinfile:
    dest: /etc/ssh/ssh_config
    state: present
    line: "StrictHostKeyChecking no"

- name: install ceph mons
  shell: /usr/bin/ceph-deploy new cephadmin cephmon && echo "done"

- name: set cluster config
  lineinfile: 
    path: ~/ceph.conf
    line: "osd_pool_default_size = 2"
    state: present

- name: change rgw default port in cephconfig
  blockinfile: 
    dest=~/ceph.conf
    content="[client.rgw.cephrgw1]\n
      rgw_frontends = \"civetweb port=8080\"\n
      [client.rgw.cephrgw2]\n
      rgw_frontends = \"civetweb port=8080\"\n"

- name: install ceph cluster
  shell: /usr/bin/ceph-deploy install cephadmin cephmon cephosd1 cephosd2 cephosd3 cephrgw1 cephrgw2 && echo "done" 

- name: create ceph mons
  shell: /usr/bin/ceph-deploy mon create-initial && echo "done"
